### ISSUE TITLE
Landing Pageにアニメーションを組み込む

### ISSUE THREAD

**Issue by kazu-S-1110** [yassun-youtube/the-hack-2022-nov-team-2#8]
参考
https://qiita.com/nemutas/items/6202b3f8458376ab79b6

**Comment by neka-nat** [comment]
アニメーションのサンプルをここからとってきてとりあえず描画してみる
https://www.mixamo.com/
実際ポケモンを動かそうと思ったら、リグとアニメーションの入った3Dのポケモンモデルが必要になる

**Comment by neka-nat** [comment]
3Dではなくてタイトルアニメーションでよいのでは？
例
* ロゴの赤い輪が回転する
* ロゴが動く

ツール
https://react-spring.dev/

**Comment by kazu-S-1110** [comment]
タイトル変えました

**Comment by neka-nat** [comment]
nextjsでのページ遷移とかがよく分かっておらず、、
とりあえず、メインのページに描画してみました。
結局tailwindでアニメーション作ってます。

https://user-images.githubusercontent.com/991515/206404925-b91b8eed-ee54-4cc8-9f30-c0189d847599.mp4

**Comment by kazu-S-1110** [comment]
@neka-nat 
> nextjsでのページ遷移とかがよく分かっておらず、、

今回の肝になるので理解しとくとあとあと良いかと😄
これとか参考になると思います！
https://vercel.com/templates/next.js/app-directory

tailwindでアニメーション！
いいですね！
