### ISSUE TITLE
aboutPageの実装

### ISSUE THREAD

**Issue by kazu-S-1110** [yassun-youtube/the-hack-2022-nov-team-2#9]
- [ ] なんの目的で作ったか
- [ ] 技術スタックは何か
- [ ] メンバーは
- [ ] 実装時期は

これぐらい載せればいいかな

**Comment by kazu-S-1110** [comment]
もしデザインが湧かなければ軽くデザインを作成するので言って頂ければと思います

**Comment by maeken6319** [comment]
いい感じのデザインがあれば教えてください。

**Comment by kazu-S-1110** [comment]
<img width="1301" alt="CleanShot 2022-12-11 at 11 55 09@2x" src="https://user-images.githubusercontent.com/67362767/206884154-6ca032c0-cda0-483a-984f-d65ca9588c9b.png">
ざっくりとこんな感じでいいと思います。
ポケモンの部分はお好きなポケモンをランダムに置けばいいかなと！

https://www.figma.com/file/soyweTjPs6YKalW5NJblmA/Poke-blend?node-id=0%3A1&t=BzJINXrt8s2on60s-1

**Comment by kazu-S-1110** [comment]
まじで数分で作ったので適宜変えたいと思ったら変えていただいて問題ないです。
文字サイズとか色味とかが微妙なのでそこらへんはよしなにやっていただけると助かります

**Comment by maeken6319** [comment]
AboutPage追加しました

https://github.com/yassun-youtube/the-hack-2022-nov-team-2/pull/28

**Comment by kazu-S-1110** [comment]
close via #28
